{
  "artifacts": [],
  "command": "main",
  "experiment": {
    "base_dir": "/home/shared/projects/MAML_Investigation/code/unimodal/nonlinear",
    "dependencies": [
      "matplotlib==3.5.0",
      "numpy==1.20.3",
      "sacred==0.8.2",
      "torch==1.10.0+cpu"
    ],
    "mainfile": "EE_fix.py",
    "name": "unimodal-nonlinear",
    "repositories": [
      {
        "commit": "83ca7e4dbcd09e11930b580ba82dc58c0da2414f",
        "dirty": true,
        "url": "git@github.com:taylanot/PhD.git"
      },
      {
        "commit": "83ca7e4dbcd09e11930b580ba82dc58c0da2414f",
        "dirty": true,
        "url": "git@github.com:taylanot/PhD.git"
      },
      {
        "commit": "83ca7e4dbcd09e11930b580ba82dc58c0da2414f",
        "dirty": true,
        "url": "git@github.com:taylanot/PhD.git"
      }
    ],
    "sources": [
      [
        "EE_fix.py",
        "_sources/EE_fix_24d9c6a998220835ea8e2db59d7e658b.py"
      ],
      [
        "models.py",
        "_sources/models_7d56799fa7d127b9b97de24933a2b5de.py"
      ],
      [
        "networks.py",
        "_sources/networks_a9ff992d69e818570d400603e2c6f240.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/usr/local/lib/python3.8/dist-packages/sacred/config/captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"EE_fix.py\", line 248, in main\n    result = EE(model_tag, run_tag, config, seed)\n",
    "  File \"EE_fix.py\", line 232, in EE\n    err.append(Error(run_config, seed, hyper))\n",
    "  File \"EE_fix.py\", line 190, in EE_MAML\n    model.fit((xtrains[i][j],ytrains[i][j]), lr=hyper, load=True, n_iter=var.n_iter)\n",
    "  File \"/home/shared/projects/MAML_Investigation/code/unimodal/nonlinear/networks.py\", line 59, in fit\n    self.load()\n",
    "  File \"/home/shared/projects/MAML_Investigation/code/unimodal/nonlinear/networks.py\", line 76, in load\n    self.load_state_dict(torch.load(path),strict=False)\n",
    "  File \"/usr/local/lib/python3.8/dist-packages/torch/serialization.py\", line 594, in load\n    with _open_file_like(f, 'rb') as opened_file:\n",
    "  File \"/usr/local/lib/python3.8/dist-packages/torch/serialization.py\", line 230, in _open_file_like\n    return _open_file(name_or_buffer, mode)\n",
    "  File \"/usr/local/lib/python3.8/dist-packages/torch/serialization.py\", line 211, in __init__\n    super(_open_file, self).__init__(open(name, mode))\n",
    "FileNotFoundError: [Errno 2] No such file or directory: 'model.pt'\n"
  ],
  "heartbeat": "2022-08-28T21:08:50.037490",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz",
    "hostname": "94fc0411525c",
    "os": [
      "Linux",
      "Linux-5.15.0-46-generic-x86_64-with-glibc2.29"
    ],
    "python_version": "3.8.10"
  },
  "meta": {
    "command": "main",
    "options": {
      "--beat-interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print-config": false,
      "--priority": null,
      "--queue": false,
      "--s3": null,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2022-08-28T21:08:50.008002",
  "status": "FAILED",
  "stop_time": "2022-08-28T21:08:50.038436"
}